---
title: Fladderende papegaai
hero_image: images/banner.png
description: Maak een spel waarin je een papegaai langs bewegende obstakels leidt
listed: true
copyedit: true
version: 4.1
last_tested: 2018-10-09
steps:
- title: Inleiding
  completion: engaged
- title: Voeg de pijpen toe
- title: 'Uitdaging: betere pijpen maken'
  challenge: true
- title: Laat de pijpen bewegen
- title: Laat Flappy vallen
- title: Laat Flappy vliegen
- title: Neem botsingen waar
  completion: internal
- title: Een score toevoegen
- title: 'Uitdaging: pas de moeilijkheidsgraad aan'
  challenge: true
- title: 'Uitdaging: voeg een topscore toe'
  challenge: true
- title: Wat kun je verder nog doen?
