title: Flappy Parrot
hero_image: images/banner.png
description: Create a game in which you have to guide a parrot around scrolling pipes to score points
original_url: https://codeclubprojects.org/en-GB/scratch/flappy-parrot
theme: green # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
listed: true
ingredient: false
copyedit: true
duration: 2
interests: games, graphics, animals
technology: scratch
steps:
- title: Introduction
- title: What you will need
- title: Add the pipes
- title: Make the pipes move
- title: Make Flappy fall
- title: Make Flappy fly
- title: Detect collision with the pipes
- title: Add scoring
- title: 'Challenge: adjust the difficulty'
- title: 'Challenge: add a high score'
